"""
Countries, and the clocks they keep.

The time zone setting used to be the raw IANA list - two thousand-odd
entries reading "Indian/Chagos", "America/Argentina/Catamarca",
"Etc/GMT+7". Those names are addresses in a database, not answers to the
question the page is actually asking, which is "where is this cafe?".
Somebody running a cafe in Delhi should find India, not have to know
that India's clock is filed under Kolkata.

So the picker asks for a country. Most countries keep one clock and are
one line. The two dozen that keep several list them, because there is no
honest way to collapse them: Brazil really is four hours wide, and an
"Australia" that quietly meant Sydney would tell Perth the wrong time
twice a day.

Nothing here is authority. IANA is, and every zone below is checked
against the ones this machine actually has before it reaches a page - a
name that is wrong or has been retired drops out rather than being
offered. See timezone_choices() in app.py.

The zone is what gets stored; the country is only how it was chosen. So
correcting a country's name here can never move a cafe's clock.
"""

# (country, [zones]). One zone means the country is offered by name
# alone; several means each is offered as "Country - City".
COUNTRY_ZONES = [
    # ---- Africa ----
    ("Algeria", ["Africa/Algiers"]),
    ("Angola", ["Africa/Luanda"]),
    ("Benin", ["Africa/Porto-Novo"]),
    ("Botswana", ["Africa/Gaborone"]),
    ("Burkina Faso", ["Africa/Ouagadougou"]),
    ("Burundi", ["Africa/Bujumbura"]),
    ("Cabo Verde", ["Atlantic/Cape_Verde"]),
    ("Cameroon", ["Africa/Douala"]),
    ("Central African Republic", ["Africa/Bangui"]),
    ("Chad", ["Africa/Ndjamena"]),
    ("Comoros", ["Indian/Comoro"]),
    ("Congo - Brazzaville", ["Africa/Brazzaville"]),
    ("Congo - Kinshasa", ["Africa/Kinshasa", "Africa/Lubumbashi"]),
    ("Côte d'Ivoire", ["Africa/Abidjan"]),
    ("Djibouti", ["Africa/Djibouti"]),
    ("Egypt", ["Africa/Cairo"]),
    ("Equatorial Guinea", ["Africa/Malabo"]),
    ("Eritrea", ["Africa/Asmara"]),
    ("Eswatini", ["Africa/Mbabane"]),
    ("Ethiopia", ["Africa/Addis_Ababa"]),
    ("Gabon", ["Africa/Libreville"]),
    ("Gambia", ["Africa/Banjul"]),
    ("Ghana", ["Africa/Accra"]),
    ("Guinea", ["Africa/Conakry"]),
    ("Guinea-Bissau", ["Africa/Bissau"]),
    ("Kenya", ["Africa/Nairobi"]),
    ("Lesotho", ["Africa/Maseru"]),
    ("Liberia", ["Africa/Monrovia"]),
    ("Libya", ["Africa/Tripoli"]),
    ("Madagascar", ["Indian/Antananarivo"]),
    ("Malawi", ["Africa/Blantyre"]),
    ("Mali", ["Africa/Bamako"]),
    ("Mauritania", ["Africa/Nouakchott"]),
    ("Mauritius", ["Indian/Mauritius"]),
    ("Mayotte", ["Indian/Mayotte"]),
    ("Morocco", ["Africa/Casablanca"]),
    ("Mozambique", ["Africa/Maputo"]),
    ("Namibia", ["Africa/Windhoek"]),
    ("Niger", ["Africa/Niamey"]),
    ("Nigeria", ["Africa/Lagos"]),
    ("Réunion", ["Indian/Reunion"]),
    ("Rwanda", ["Africa/Kigali"]),
    ("São Tomé and Príncipe", ["Africa/Sao_Tome"]),
    ("Senegal", ["Africa/Dakar"]),
    ("Seychelles", ["Indian/Mahe"]),
    ("Sierra Leone", ["Africa/Freetown"]),
    ("Somalia", ["Africa/Mogadishu"]),
    ("South Africa", ["Africa/Johannesburg"]),
    ("South Sudan", ["Africa/Juba"]),
    ("Sudan", ["Africa/Khartoum"]),
    ("Tanzania", ["Africa/Dar_es_Salaam"]),
    ("Togo", ["Africa/Lome"]),
    ("Tunisia", ["Africa/Tunis"]),
    ("Uganda", ["Africa/Kampala"]),
    ("Western Sahara", ["Africa/El_Aaiun"]),
    ("Zambia", ["Africa/Lusaka"]),
    ("Zimbabwe", ["Africa/Harare"]),

    # ---- The Americas ----
    ("Anguilla", ["America/Anguilla"]),
    ("Antigua and Barbuda", ["America/Antigua"]),
    ("Argentina", [
        "America/Argentina/Buenos_Aires", "America/Argentina/Cordoba",
        "America/Argentina/Mendoza", "America/Argentina/Salta",
        "America/Argentina/Tucuman", "America/Argentina/Ushuaia",
    ]),
    ("Aruba", ["America/Aruba"]),
    ("Bahamas", ["America/Nassau"]),
    ("Barbados", ["America/Barbados"]),
    ("Belize", ["America/Belize"]),
    ("Bermuda", ["Atlantic/Bermuda"]),
    ("Bolivia", ["America/La_Paz"]),
    ("Brazil", [
        "America/Sao_Paulo", "America/Bahia", "America/Fortaleza",
        "America/Recife", "America/Belem", "America/Manaus",
        "America/Cuiaba", "America/Campo_Grande", "America/Porto_Velho",
        "America/Boa_Vista", "America/Rio_Branco", "America/Noronha",
    ]),
    ("British Virgin Islands", ["America/Tortola"]),
    ("Canada", [
        "America/St_Johns", "America/Halifax", "America/Moncton",
        "America/Toronto", "America/Winnipeg", "America/Regina",
        "America/Edmonton", "America/Vancouver", "America/Whitehorse",
        "America/Iqaluit",
    ]),
    ("Cayman Islands", ["America/Cayman"]),
    ("Chile", ["America/Santiago", "America/Punta_Arenas", "Pacific/Easter"]),
    ("Colombia", ["America/Bogota"]),
    ("Costa Rica", ["America/Costa_Rica"]),
    ("Cuba", ["America/Havana"]),
    ("Curaçao", ["America/Curacao"]),
    ("Dominica", ["America/Dominica"]),
    ("Dominican Republic", ["America/Santo_Domingo"]),
    ("Ecuador", ["America/Guayaquil", "Pacific/Galapagos"]),
    ("El Salvador", ["America/El_Salvador"]),
    ("Falkland Islands", ["Atlantic/Stanley"]),
    ("French Guiana", ["America/Cayenne"]),
    ("Greenland", [
        "America/Nuuk", "America/Danmarkshavn", "America/Scoresbysund",
        "America/Thule",
    ]),
    ("Grenada", ["America/Grenada"]),
    ("Guadeloupe", ["America/Guadeloupe"]),
    ("Guatemala", ["America/Guatemala"]),
    ("Guyana", ["America/Guyana"]),
    ("Haiti", ["America/Port-au-Prince"]),
    ("Honduras", ["America/Tegucigalpa"]),
    ("Jamaica", ["America/Jamaica"]),
    ("Martinique", ["America/Martinique"]),
    ("Mexico", [
        "America/Mexico_City", "America/Cancun", "America/Merida",
        "America/Monterrey", "America/Chihuahua", "America/Mazatlan",
        "America/Hermosillo", "America/Tijuana",
    ]),
    ("Montserrat", ["America/Montserrat"]),
    ("Nicaragua", ["America/Managua"]),
    ("Panama", ["America/Panama"]),
    ("Paraguay", ["America/Asuncion"]),
    ("Peru", ["America/Lima"]),
    ("Puerto Rico", ["America/Puerto_Rico"]),
    ("Saint Barthélemy", ["America/St_Barthelemy"]),
    ("Saint Kitts and Nevis", ["America/St_Kitts"]),
    ("Saint Lucia", ["America/St_Lucia"]),
    ("Saint Martin", ["America/Marigot"]),
    ("Saint Pierre and Miquelon", ["America/Miquelon"]),
    ("Saint Vincent and the Grenadines", ["America/St_Vincent"]),
    ("Sint Maarten", ["America/Lower_Princes"]),
    ("Suriname", ["America/Paramaribo"]),
    ("Trinidad and Tobago", ["America/Port_of_Spain"]),
    ("Turks and Caicos Islands", ["America/Grand_Turk"]),
    ("United States", [
        "America/New_York", "America/Detroit",
        "America/Indiana/Indianapolis", "America/Chicago",
        "America/Denver", "America/Phoenix", "America/Los_Angeles",
        "America/Anchorage", "America/Juneau", "America/Adak",
        "Pacific/Honolulu",
    ]),
    ("Uruguay", ["America/Montevideo"]),
    ("U.S. Virgin Islands", ["America/St_Thomas"]),
    ("Venezuela", ["America/Caracas"]),

    # ---- Asia ----
    ("Afghanistan", ["Asia/Kabul"]),
    ("Armenia", ["Asia/Yerevan"]),
    ("Azerbaijan", ["Asia/Baku"]),
    ("Bahrain", ["Asia/Bahrain"]),
    ("Bangladesh", ["Asia/Dhaka"]),
    ("Bhutan", ["Asia/Thimphu"]),
    ("British Indian Ocean Territory", ["Indian/Chagos"]),
    ("Brunei", ["Asia/Brunei"]),
    ("Cambodia", ["Asia/Phnom_Penh"]),
    ("China", ["Asia/Shanghai", "Asia/Urumqi"]),
    ("Cyprus", ["Asia/Nicosia", "Asia/Famagusta"]),
    ("Georgia", ["Asia/Tbilisi"]),
    ("Hong Kong", ["Asia/Hong_Kong"]),
    ("India", ["Asia/Kolkata"]),
    ("Indonesia", [
        "Asia/Jakarta", "Asia/Pontianak", "Asia/Makassar", "Asia/Jayapura",
    ]),
    ("Iran", ["Asia/Tehran"]),
    ("Iraq", ["Asia/Baghdad"]),
    ("Israel", ["Asia/Jerusalem"]),
    ("Japan", ["Asia/Tokyo"]),
    ("Jordan", ["Asia/Amman"]),
    ("Kazakhstan", [
        "Asia/Almaty", "Asia/Qostanay", "Asia/Qyzylorda", "Asia/Aqtobe",
        "Asia/Aqtau", "Asia/Atyrau", "Asia/Oral",
    ]),
    ("Kuwait", ["Asia/Kuwait"]),
    ("Kyrgyzstan", ["Asia/Bishkek"]),
    ("Laos", ["Asia/Vientiane"]),
    ("Lebanon", ["Asia/Beirut"]),
    ("Macao", ["Asia/Macau"]),
    ("Malaysia", ["Asia/Kuala_Lumpur", "Asia/Kuching"]),
    ("Maldives", ["Indian/Maldives"]),
    ("Mongolia", ["Asia/Ulaanbaatar", "Asia/Hovd", "Asia/Choibalsan"]),
    ("Myanmar", ["Asia/Yangon"]),
    ("Nepal", ["Asia/Kathmandu"]),
    ("North Korea", ["Asia/Pyongyang"]),
    ("Oman", ["Asia/Muscat"]),
    ("Pakistan", ["Asia/Karachi"]),
    ("Palestine", ["Asia/Gaza", "Asia/Hebron"]),
    ("Philippines", ["Asia/Manila"]),
    ("Qatar", ["Asia/Qatar"]),
    ("Russia", [
        "Europe/Kaliningrad", "Europe/Moscow", "Europe/Volgograd",
        "Europe/Samara", "Asia/Yekaterinburg", "Asia/Omsk",
        "Asia/Novosibirsk", "Asia/Krasnoyarsk", "Asia/Irkutsk",
        "Asia/Yakutsk", "Asia/Vladivostok", "Asia/Magadan",
        "Asia/Sakhalin", "Asia/Kamchatka",
    ]),
    ("Saudi Arabia", ["Asia/Riyadh"]),
    ("Singapore", ["Asia/Singapore"]),
    ("South Korea", ["Asia/Seoul"]),
    ("Sri Lanka", ["Asia/Colombo"]),
    ("Syria", ["Asia/Damascus"]),
    ("Taiwan", ["Asia/Taipei"]),
    ("Tajikistan", ["Asia/Dushanbe"]),
    ("Thailand", ["Asia/Bangkok"]),
    ("Timor-Leste", ["Asia/Dili"]),
    ("Turkey", ["Europe/Istanbul"]),
    ("Turkmenistan", ["Asia/Ashgabat"]),
    ("United Arab Emirates", ["Asia/Dubai"]),
    ("Uzbekistan", ["Asia/Tashkent", "Asia/Samarkand"]),
    ("Vietnam", ["Asia/Ho_Chi_Minh"]),
    ("Yemen", ["Asia/Aden"]),

    # ---- Europe ----
    ("Åland Islands", ["Europe/Mariehamn"]),
    ("Albania", ["Europe/Tirane"]),
    ("Andorra", ["Europe/Andorra"]),
    ("Austria", ["Europe/Vienna"]),
    ("Belarus", ["Europe/Minsk"]),
    ("Belgium", ["Europe/Brussels"]),
    ("Bosnia and Herzegovina", ["Europe/Sarajevo"]),
    ("Bulgaria", ["Europe/Sofia"]),
    ("Croatia", ["Europe/Zagreb"]),
    ("Czechia", ["Europe/Prague"]),
    ("Denmark", ["Europe/Copenhagen"]),
    ("Estonia", ["Europe/Tallinn"]),
    ("Faroe Islands", ["Atlantic/Faroe"]),
    ("Finland", ["Europe/Helsinki"]),
    ("France", ["Europe/Paris"]),
    ("Germany", ["Europe/Berlin"]),
    ("Gibraltar", ["Europe/Gibraltar"]),
    ("Greece", ["Europe/Athens"]),
    ("Guernsey", ["Europe/Guernsey"]),
    ("Hungary", ["Europe/Budapest"]),
    ("Iceland", ["Atlantic/Reykjavik"]),
    ("Ireland", ["Europe/Dublin"]),
    ("Isle of Man", ["Europe/Isle_of_Man"]),
    ("Italy", ["Europe/Rome"]),
    ("Jersey", ["Europe/Jersey"]),
    ("Latvia", ["Europe/Riga"]),
    ("Liechtenstein", ["Europe/Vaduz"]),
    ("Lithuania", ["Europe/Vilnius"]),
    ("Luxembourg", ["Europe/Luxembourg"]),
    ("Malta", ["Europe/Malta"]),
    ("Moldova", ["Europe/Chisinau"]),
    ("Monaco", ["Europe/Monaco"]),
    ("Montenegro", ["Europe/Podgorica"]),
    ("Netherlands", ["Europe/Amsterdam"]),
    ("North Macedonia", ["Europe/Skopje"]),
    ("Norway", ["Europe/Oslo"]),
    ("Poland", ["Europe/Warsaw"]),
    ("Portugal", ["Europe/Lisbon", "Atlantic/Madeira", "Atlantic/Azores"]),
    ("Romania", ["Europe/Bucharest"]),
    ("San Marino", ["Europe/San_Marino"]),
    ("Serbia", ["Europe/Belgrade"]),
    ("Slovakia", ["Europe/Bratislava"]),
    ("Slovenia", ["Europe/Ljubljana"]),
    ("Spain", ["Europe/Madrid", "Africa/Ceuta", "Atlantic/Canary"]),
    ("Svalbard and Jan Mayen", ["Arctic/Longyearbyen"]),
    ("Sweden", ["Europe/Stockholm"]),
    ("Switzerland", ["Europe/Zurich"]),
    ("Ukraine", ["Europe/Kyiv"]),
    ("United Kingdom", ["Europe/London"]),
    ("Vatican City", ["Europe/Vatican"]),

    # ---- Oceania ----
    ("American Samoa", ["Pacific/Pago_Pago"]),
    ("Australia", [
        "Australia/Sydney", "Australia/Melbourne", "Australia/Brisbane",
        "Australia/Adelaide", "Australia/Perth", "Australia/Hobart",
        "Australia/Darwin", "Australia/Broken_Hill", "Australia/Lord_Howe",
        "Australia/Eucla",
    ]),
    ("Christmas Island", ["Indian/Christmas"]),
    ("Cocos (Keeling) Islands", ["Indian/Cocos"]),
    ("Cook Islands", ["Pacific/Rarotonga"]),
    ("Fiji", ["Pacific/Fiji"]),
    ("French Polynesia", [
        "Pacific/Tahiti", "Pacific/Marquesas", "Pacific/Gambier",
    ]),
    ("Guam", ["Pacific/Guam"]),
    ("Kiribati", ["Pacific/Tarawa", "Pacific/Kanton", "Pacific/Kiritimati"]),
    ("Marshall Islands", ["Pacific/Majuro", "Pacific/Kwajalein"]),
    ("Micronesia", ["Pacific/Chuuk", "Pacific/Pohnpei", "Pacific/Kosrae"]),
    ("Nauru", ["Pacific/Nauru"]),
    ("New Caledonia", ["Pacific/Noumea"]),
    ("New Zealand", ["Pacific/Auckland", "Pacific/Chatham"]),
    ("Niue", ["Pacific/Niue"]),
    ("Norfolk Island", ["Pacific/Norfolk"]),
    ("Northern Mariana Islands", ["Pacific/Saipan"]),
    ("Palau", ["Pacific/Palau"]),
    ("Papua New Guinea", [
        "Pacific/Port_Moresby", "Pacific/Bougainville",
    ]),
    ("Pitcairn Islands", ["Pacific/Pitcairn"]),
    ("Samoa", ["Pacific/Apia"]),
    ("Solomon Islands", ["Pacific/Guadalcanal"]),
    ("Tokelau", ["Pacific/Fakaofo"]),
    ("Tonga", ["Pacific/Tongatapu"]),
    ("Tuvalu", ["Pacific/Funafuti"]),
    ("Vanuatu", ["Pacific/Efate"]),
    ("Wallis and Futuna", ["Pacific/Wallis"]),
]


# Names a browser may report that the list above files under something
# else. A browser in Delhi says "Asia/Calcutta"; the list, and IANA
# itself these days, says "Asia/Kolkata". Both are real and both give the
# same time, but only one of them is in the picker - and a cafe whose
# stored zone is not in the picker opens the page to find nothing chosen.
#
# Only aliases that point somewhere the list actually offers. Anything
# else is left exactly as it is: an unrecognised name that the machine
# still resolves keeps working, and the picker carries it as an extra
# entry rather than dropping it.
ZONE_ALIASES = {
    "Asia/Calcutta": "Asia/Kolkata",
    "Asia/Katmandu": "Asia/Kathmandu",
    "Asia/Rangoon": "Asia/Yangon",
    "Asia/Saigon": "Asia/Ho_Chi_Minh",
    "Asia/Dacca": "Asia/Dhaka",
    "Asia/Thimbu": "Asia/Thimphu",
    "Asia/Ashkhabad": "Asia/Ashgabat",
    "Asia/Ulan_Bator": "Asia/Ulaanbaatar",
    "Asia/Chongqing": "Asia/Shanghai",
    "Asia/Chungking": "Asia/Shanghai",
    "Asia/Harbin": "Asia/Shanghai",
    "Asia/Kashgar": "Asia/Urumqi",
    "Asia/Macao": "Asia/Macau",
    "Asia/Tel_Aviv": "Asia/Jerusalem",
    "Asia/Istanbul": "Europe/Istanbul",
    "Europe/Nicosia": "Asia/Nicosia",
    "Europe/Kiev": "Europe/Kyiv",
    "Europe/Uzhgorod": "Europe/Kyiv",
    "Europe/Zaporozhye": "Europe/Kyiv",
    "Europe/Belfast": "Europe/London",
    "Europe/Tiraspol": "Europe/Chisinau",
    "America/Buenos_Aires": "America/Argentina/Buenos_Aires",
    "America/Cordoba": "America/Argentina/Cordoba",
    "America/Rosario": "America/Argentina/Cordoba",
    "America/Mendoza": "America/Argentina/Mendoza",
    "America/Jujuy": "America/Argentina/Salta",
    "America/Catamarca": "America/Argentina/Salta",
    "America/Indianapolis": "America/Indiana/Indianapolis",
    "America/Fort_Wayne": "America/Indiana/Indianapolis",
    "America/Louisville": "America/New_York",
    "America/Montreal": "America/Toronto",
    "America/Nipigon": "America/Toronto",
    "America/Thunder_Bay": "America/Toronto",
    "America/Rainy_River": "America/Winnipeg",
    "America/Yellowknife": "America/Edmonton",
    "America/Atikokan": "America/Panama",
    "America/Coral_Harbour": "America/Panama",
    "America/Santa_Isabel": "America/Tijuana",
    "America/Ensenada": "America/Tijuana",
    "America/Godthab": "America/Nuuk",
    "America/Virgin": "America/St_Thomas",
    "America/Shiprock": "America/Denver",
    "America/Knox_IN": "America/Chicago",
    "Africa/Timbuktu": "Africa/Bamako",
    "Africa/Asmera": "Africa/Asmara",
    "Atlantic/Jan_Mayen": "Arctic/Longyearbyen",
    "Atlantic/Faeroe": "Atlantic/Faroe",
    "Pacific/Ponape": "Pacific/Pohnpei",
    "Pacific/Truk": "Pacific/Chuuk",
    "Pacific/Yap": "Pacific/Chuuk",
    "Pacific/Samoa": "Pacific/Pago_Pago",
    "Pacific/Johnston": "Pacific/Honolulu",
    "Pacific/Enderbury": "Pacific/Kanton",
    "Australia/ACT": "Australia/Sydney",
    "Australia/NSW": "Australia/Sydney",
    "Australia/Canberra": "Australia/Sydney",
    "Australia/Victoria": "Australia/Melbourne",
    "Australia/Queensland": "Australia/Brisbane",
    "Australia/South": "Australia/Adelaide",
    "Australia/West": "Australia/Perth",
    "Australia/Tasmania": "Australia/Hobart",
    "Australia/North": "Australia/Darwin",
    "Australia/LHI": "Australia/Lord_Howe",
    "Australia/Yancowinna": "Australia/Broken_Hill",
    # The short country-code spellings, which some browsers still use.
    "Hongkong": "Asia/Hong_Kong",
    "Iceland": "Atlantic/Reykjavik",
    "Israel": "Asia/Jerusalem",
    "Jamaica": "America/Jamaica",
    "Japan": "Asia/Tokyo",
    "Kwajalein": "Pacific/Kwajalein",
    "Libya": "Africa/Tripoli",
    "Navajo": "America/Denver",
    "Poland": "Europe/Warsaw",
    "Portugal": "Europe/Lisbon",
    "Singapore": "Asia/Singapore",
    "Turkey": "Europe/Istanbul",
    "Egypt": "Africa/Cairo",
    "Eire": "Europe/Dublin",
    "Cuba": "America/Havana",
    "GB": "Europe/London",
    "GB-Eire": "Europe/London",
    "PRC": "Asia/Shanghai",
    "ROC": "Asia/Taipei",
    "ROK": "Asia/Seoul",
    "NZ": "Pacific/Auckland",
    "NZ-CHAT": "Pacific/Chatham",
    "W-SU": "Europe/Moscow",
    "Zulu": "UTC",
    "Universal": "UTC",
    "Greenwich": "UTC",
    "GMT": "UTC",
    "GMT0": "UTC",
    "GMT+0": "UTC",
    "GMT-0": "UTC",
    "Etc/UTC": "UTC",
    "Etc/GMT": "UTC",
    "Etc/Greenwich": "UTC",
    "Etc/Universal": "UTC",
    "Etc/Zulu": "UTC",
}


def city_of(zone):
    """
    The part of a zone name people would recognise.

    "America/Argentina/Buenos_Aires" -> "Buenos Aires". Only ever shown
    beside a country that keeps more than one clock, where the country's
    name alone would not say which.
    """
    return zone.rsplit("/", 1)[-1].replace("_", " ")


# ======================================================================
# Dial codes, and how many digits follow them
# ======================================================================
# The phone field asks for a country and then wants exactly the number
# of digits that country uses, so a mistyped number is caught where it
# is typed rather than when an access code fails to arrive months later.
#
# The lengths are of the NATIONAL number - what is left after the dial
# code, and after the trunk zero some countries write at the front of a
# number at home. A country whose numbers genuinely vary lists each
# length it uses, because refusing a real number is worse than
# accepting an odd one.
#
# Dial codes are shared: +1 is twenty-odd countries, +7 is two, +44
# covers the Isle of Man and the Channel Islands. So the country is
# what gets picked and the code is what gets stored, never the other
# way round.
#
# (country, dial code, lengths the national number may be)
DIAL_CODES = [
    ('Algeria', '213', (9,)),
    ('Angola', '244', (9,)),
    ('Benin', '229', (8, 10)),
    ('Botswana', '267', (7, 8)),
    ('Burkina Faso', '226', (8,)),
    ('Burundi', '257', (8,)),
    ('Cabo Verde', '238', (7,)),
    ('Cameroon', '237', (9,)),
    ('Central African Republic', '236', (8,)),
    ('Chad', '235', (8,)),
    ('Comoros', '269', (7,)),
    ('Congo - Brazzaville', '242', (9,)),
    ('Congo - Kinshasa', '243', (9,)),
    ("Côte d'Ivoire", '225', (10,)),
    ('Djibouti', '253', (8,)),
    ('Egypt', '20', (10,)),
    ('Equatorial Guinea', '240', (9,)),
    ('Eritrea', '291', (7,)),
    ('Eswatini', '268', (8,)),
    ('Ethiopia', '251', (9,)),
    ('Gabon', '241', (7, 8)),
    ('Gambia', '220', (7,)),
    ('Ghana', '233', (9,)),
    ('Guinea', '224', (9,)),
    ('Guinea-Bissau', '245', (7,)),
    ('Kenya', '254', (9,)),
    ('Lesotho', '266', (8,)),
    ('Liberia', '231', (7, 8, 9)),
    ('Libya', '218', (9,)),
    ('Madagascar', '261', (9,)),
    ('Malawi', '265', (7, 9)),
    ('Mali', '223', (8,)),
    ('Mauritania', '222', (8,)),
    ('Mauritius', '230', (7, 8)),
    ('Mayotte', '262', (9,)),
    ('Morocco', '212', (9,)),
    ('Mozambique', '258', (9,)),
    ('Namibia', '264', (7, 8, 9)),
    ('Niger', '227', (8,)),
    ('Nigeria', '234', (8, 10)),
    ('Réunion', '262', (9,)),
    ('Rwanda', '250', (9,)),
    ('São Tomé and Príncipe', '239', (7,)),
    ('Senegal', '221', (9,)),
    ('Seychelles', '248', (7,)),
    ('Sierra Leone', '232', (8,)),
    ('Somalia', '252', (7, 8, 9)),
    ('South Africa', '27', (9,)),
    ('South Sudan', '211', (9,)),
    ('Sudan', '249', (9,)),
    ('Tanzania', '255', (9,)),
    ('Togo', '228', (8,)),
    ('Tunisia', '216', (8,)),
    ('Uganda', '256', (9,)),
    ('Western Sahara', '212', (9,)),
    ('Zambia', '260', (9,)),
    ('Zimbabwe', '263', (9,)),
    ('Anguilla', '1', (10,)),
    ('Antigua and Barbuda', '1', (10,)),
    ('Argentina', '54', (10,)),
    ('Aruba', '297', (7,)),
    ('Bahamas', '1', (10,)),
    ('Barbados', '1', (10,)),
    ('Belize', '501', (7,)),
    ('Bermuda', '1', (10,)),
    ('Bolivia', '591', (8,)),
    ('Brazil', '55', (10, 11)),
    ('British Virgin Islands', '1', (10,)),
    ('Canada', '1', (10,)),
    ('Cayman Islands', '1', (10,)),
    ('Chile', '56', (9,)),
    ('Colombia', '57', (10,)),
    ('Costa Rica', '506', (8,)),
    ('Cuba', '53', (8,)),
    ('Curaçao', '599', (7, 8)),
    ('Dominica', '1', (10,)),
    ('Dominican Republic', '1', (10,)),
    ('Ecuador', '593', (9,)),
    ('El Salvador', '503', (8,)),
    ('Falkland Islands', '500', (5,)),
    ('French Guiana', '594', (9,)),
    ('Greenland', '299', (6,)),
    ('Grenada', '1', (10,)),
    ('Guadeloupe', '590', (9,)),
    ('Guatemala', '502', (8,)),
    ('Guyana', '592', (7,)),
    ('Haiti', '509', (8,)),
    ('Honduras', '504', (8,)),
    ('Jamaica', '1', (10,)),
    ('Martinique', '596', (9,)),
    ('Mexico', '52', (10,)),
    ('Montserrat', '1', (10,)),
    ('Nicaragua', '505', (8,)),
    ('Panama', '507', (7, 8)),
    ('Paraguay', '595', (9,)),
    ('Peru', '51', (9,)),
    ('Puerto Rico', '1', (10,)),
    ('Saint Barthélemy', '590', (9,)),
    ('Saint Kitts and Nevis', '1', (10,)),
    ('Saint Lucia', '1', (10,)),
    ('Saint Martin', '590', (9,)),
    ('Saint Pierre and Miquelon', '508', (6,)),
    ('Saint Vincent and the Grenadines', '1', (10,)),
    ('Sint Maarten', '1', (10,)),
    ('Suriname', '597', (6, 7)),
    ('Trinidad and Tobago', '1', (10,)),
    ('Turks and Caicos Islands', '1', (10,)),
    ('United States', '1', (10,)),
    ('Uruguay', '598', (8,)),
    ('U.S. Virgin Islands', '1', (10,)),
    ('Venezuela', '58', (10,)),
    ('Afghanistan', '93', (9,)),
    ('Armenia', '374', (8,)),
    ('Azerbaijan', '994', (9,)),
    ('Bahrain', '973', (8,)),
    ('Bangladesh', '880', (10,)),
    ('Bhutan', '975', (8,)),
    ('British Indian Ocean Territory', '246', (7,)),
    ('Brunei', '673', (7,)),
    ('Cambodia', '855', (8, 9)),
    ('China', '86', (11,)),
    ('Cyprus', '357', (8,)),
    ('Georgia', '995', (9,)),
    ('Hong Kong', '852', (8,)),
    ('India', '91', (10,)),
    ('Indonesia', '62', (9, 10, 11, 12)),
    ('Iran', '98', (10,)),
    ('Iraq', '964', (10,)),
    ('Israel', '972', (9,)),
    ('Japan', '81', (10,)),
    ('Jordan', '962', (9,)),
    ('Kazakhstan', '7', (10,)),
    ('Kuwait', '965', (8,)),
    ('Kyrgyzstan', '996', (9,)),
    ('Laos', '856', (8, 9, 10)),
    ('Lebanon', '961', (7, 8)),
    ('Macao', '853', (8,)),
    ('Malaysia', '60', (9, 10)),
    ('Maldives', '960', (7,)),
    ('Mongolia', '976', (8,)),
    ('Myanmar', '95', (8, 9, 10)),
    ('Nepal', '977', (10,)),
    ('North Korea', '850', (8, 9, 10)),
    ('Oman', '968', (8,)),
    ('Pakistan', '92', (10,)),
    ('Palestine', '970', (9,)),
    ('Philippines', '63', (10,)),
    ('Qatar', '974', (8,)),
    ('Russia', '7', (10,)),
    ('Saudi Arabia', '966', (9,)),
    ('Singapore', '65', (8,)),
    ('South Korea', '82', (9, 10)),
    ('Sri Lanka', '94', (9,)),
    ('Syria', '963', (9,)),
    ('Taiwan', '886', (9,)),
    ('Tajikistan', '992', (9,)),
    ('Thailand', '66', (9,)),
    ('Timor-Leste', '670', (7, 8)),
    ('Turkey', '90', (10,)),
    ('Turkmenistan', '993', (8,)),
    ('United Arab Emirates', '971', (9,)),
    ('Uzbekistan', '998', (9,)),
    ('Vietnam', '84', (9, 10)),
    ('Yemen', '967', (7, 8, 9)),
    ('Åland Islands', '358', (9, 10)),
    ('Albania', '355', (9,)),
    ('Andorra', '376', (6,)),
    ('Austria', '43', (10, 11)),
    ('Belarus', '375', (9,)),
    ('Belgium', '32', (9,)),
    ('Bosnia and Herzegovina', '387', (8,)),
    ('Bulgaria', '359', (9,)),
    ('Croatia', '385', (8, 9)),
    ('Czechia', '420', (9,)),
    ('Denmark', '45', (8,)),
    ('Estonia', '372', (7, 8)),
    ('Faroe Islands', '298', (6,)),
    ('Finland', '358', (9, 10)),
    ('France', '33', (9,)),
    ('Germany', '49', (10, 11)),
    ('Gibraltar', '350', (8,)),
    ('Greece', '30', (10,)),
    ('Guernsey', '44', (10,)),
    ('Hungary', '36', (9,)),
    ('Iceland', '354', (7,)),
    ('Ireland', '353', (9,)),
    ('Isle of Man', '44', (10,)),
    ('Italy', '39', (9, 10)),
    ('Jersey', '44', (10,)),
    ('Latvia', '371', (8,)),
    ('Liechtenstein', '423', (7,)),
    ('Lithuania', '370', (8,)),
    ('Luxembourg', '352', (9,)),
    ('Malta', '356', (8,)),
    ('Moldova', '373', (8,)),
    ('Monaco', '377', (8,)),
    ('Montenegro', '382', (8,)),
    ('Netherlands', '31', (9,)),
    ('North Macedonia', '389', (8,)),
    ('Norway', '47', (8,)),
    ('Poland', '48', (9,)),
    ('Portugal', '351', (9,)),
    ('Romania', '40', (9,)),
    ('San Marino', '378', (8, 9, 10)),
    ('Serbia', '381', (8, 9)),
    ('Slovakia', '421', (9,)),
    ('Slovenia', '386', (8,)),
    ('Spain', '34', (9,)),
    ('Svalbard and Jan Mayen', '47', (8,)),
    ('Sweden', '46', (9,)),
    ('Switzerland', '41', (9,)),
    ('Ukraine', '380', (9,)),
    ('United Kingdom', '44', (10,)),
    ('Vatican City', '39', (9, 10)),
    ('American Samoa', '1', (10,)),
    ('Australia', '61', (9,)),
    ('Christmas Island', '61', (9,)),
    ('Cocos (Keeling) Islands', '61', (9,)),
    ('Cook Islands', '682', (5,)),
    ('Fiji', '679', (7,)),
    ('French Polynesia', '689', (8,)),
    ('Guam', '1', (10,)),
    ('Kiribati', '686', (5, 8)),
    ('Marshall Islands', '692', (7,)),
    ('Micronesia', '691', (7,)),
    ('Nauru', '674', (7,)),
    ('New Caledonia', '687', (6,)),
    ('New Zealand', '64', (8, 9, 10)),
    ('Niue', '683', (4,)),
    ('Norfolk Island', '672', (6,)),
    ('Northern Mariana Islands', '1', (10,)),
    ('Palau', '680', (7,)),
    ('Papua New Guinea', '675', (8,)),
    ('Pitcairn Islands', '64', (8, 9)),
    ('Samoa', '685', (5, 6, 7)),
    ('Solomon Islands', '677', (5, 7)),
    ('Tokelau', '690', (4, 5)),
    ('Tonga', '676', (5, 7)),
    ('Tuvalu', '688', (5, 6)),
    ('Vanuatu', '678', (5, 7)),
    ('Wallis and Futuna', '681', (6,)),
]

_BY_COUNTRY = {country: (code, lengths)
               for country, code, lengths in DIAL_CODES}


def dial_code_of(country):
    """The dial code for a country, or None if it is not one we list."""
    found = _BY_COUNTRY.get(country)
    return found[0] if found else None


def number_lengths(country):
    """
    How many digits the national number may have, longest last.

    An unknown country gets a range wide enough for anywhere: the field
    still works, it simply cannot be strict about a place this table
    does not cover.
    """
    found = _BY_COUNTRY.get(country)
    return found[1] if found else (4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)
