"""
Countries, and the clocks they keep.

The time zone setting used to be the raw IANA list - two thousand-odd
entries reading "Indian/Chagos", "America/Argentina/Catamarca",
"Etc/GMT+7". Those names are addresses in a database, not answers to the
question the page is actually asking, which is "where is this cafe?".
Somebody running a cafe in Delhi should find India, not have to know
that India's clock is filed under Kolkata.

So the picker asks for a country. Most countries keep one clock and are
one line. The two dozen that keep several list them, because there is no
honest way to collapse them: Brazil really is four hours wide, and an
"Australia" that quietly meant Sydney would tell Perth the wrong time
twice a day.

Nothing here is authority. IANA is, and every zone below is checked
against the ones this machine actually has before it reaches a page - a
name that is wrong or has been retired drops out rather than being
offered. See timezone_choices() in app.py.

The zone is what gets stored; the country is only how it was chosen. So
correcting a country's name here can never move a cafe's clock.
"""

# (country, [zones]). One zone means the country is offered by name
# alone; several means each is offered as "Country - City".
COUNTRY_ZONES = [
    # ---- Africa ----
    ("Algeria", ["Africa/Algiers"]),
    ("Angola", ["Africa/Luanda"]),
    ("Benin", ["Africa/Porto-Novo"]),
    ("Botswana", ["Africa/Gaborone"]),
    ("Burkina Faso", ["Africa/Ouagadougou"]),
    ("Burundi", ["Africa/Bujumbura"]),
    ("Cabo Verde", ["Atlantic/Cape_Verde"]),
    ("Cameroon", ["Africa/Douala"]),
    ("Central African Republic", ["Africa/Bangui"]),
    ("Chad", ["Africa/Ndjamena"]),
    ("Comoros", ["Indian/Comoro"]),
    ("Congo - Brazzaville", ["Africa/Brazzaville"]),
    ("Congo - Kinshasa", ["Africa/Kinshasa", "Africa/Lubumbashi"]),
    ("Côte d'Ivoire", ["Africa/Abidjan"]),
    ("Djibouti", ["Africa/Djibouti"]),
    ("Egypt", ["Africa/Cairo"]),
    ("Equatorial Guinea", ["Africa/Malabo"]),
    ("Eritrea", ["Africa/Asmara"]),
    ("Eswatini", ["Africa/Mbabane"]),
    ("Ethiopia", ["Africa/Addis_Ababa"]),
    ("Gabon", ["Africa/Libreville"]),
    ("Gambia", ["Africa/Banjul"]),
    ("Ghana", ["Africa/Accra"]),
    ("Guinea", ["Africa/Conakry"]),
    ("Guinea-Bissau", ["Africa/Bissau"]),
    ("Kenya", ["Africa/Nairobi"]),
    ("Lesotho", ["Africa/Maseru"]),
    ("Liberia", ["Africa/Monrovia"]),
    ("Libya", ["Africa/Tripoli"]),
    ("Madagascar", ["Indian/Antananarivo"]),
    ("Malawi", ["Africa/Blantyre"]),
    ("Mali", ["Africa/Bamako"]),
    ("Mauritania", ["Africa/Nouakchott"]),
    ("Mauritius", ["Indian/Mauritius"]),
    ("Mayotte", ["Indian/Mayotte"]),
    ("Morocco", ["Africa/Casablanca"]),
    ("Mozambique", ["Africa/Maputo"]),
    ("Namibia", ["Africa/Windhoek"]),
    ("Niger", ["Africa/Niamey"]),
    ("Nigeria", ["Africa/Lagos"]),
    ("Réunion", ["Indian/Reunion"]),
    ("Rwanda", ["Africa/Kigali"]),
    ("São Tomé and Príncipe", ["Africa/Sao_Tome"]),
    ("Senegal", ["Africa/Dakar"]),
    ("Seychelles", ["Indian/Mahe"]),
    ("Sierra Leone", ["Africa/Freetown"]),
    ("Somalia", ["Africa/Mogadishu"]),
    ("South Africa", ["Africa/Johannesburg"]),
    ("South Sudan", ["Africa/Juba"]),
    ("Sudan", ["Africa/Khartoum"]),
    ("Tanzania", ["Africa/Dar_es_Salaam"]),
    ("Togo", ["Africa/Lome"]),
    ("Tunisia", ["Africa/Tunis"]),
    ("Uganda", ["Africa/Kampala"]),
    ("Western Sahara", ["Africa/El_Aaiun"]),
    ("Zambia", ["Africa/Lusaka"]),
    ("Zimbabwe", ["Africa/Harare"]),

    # ---- The Americas ----
    ("Anguilla", ["America/Anguilla"]),
    ("Antigua and Barbuda", ["America/Antigua"]),
    ("Argentina", [
        "America/Argentina/Buenos_Aires", "America/Argentina/Cordoba",
        "America/Argentina/Mendoza", "America/Argentina/Salta",
        "America/Argentina/Tucuman", "America/Argentina/Ushuaia",
    ]),
    ("Aruba", ["America/Aruba"]),
    ("Bahamas", ["America/Nassau"]),
    ("Barbados", ["America/Barbados"]),
    ("Belize", ["America/Belize"]),
    ("Bermuda", ["Atlantic/Bermuda"]),
    ("Bolivia", ["America/La_Paz"]),
    ("Brazil", [
        "America/Sao_Paulo", "America/Bahia", "America/Fortaleza",
        "America/Recife", "America/Belem", "America/Manaus",
        "America/Cuiaba", "America/Campo_Grande", "America/Porto_Velho",
        "America/Boa_Vista", "America/Rio_Branco", "America/Noronha",
    ]),
    ("British Virgin Islands", ["America/Tortola"]),
    ("Canada", [
        "America/St_Johns", "America/Halifax", "America/Moncton",
        "America/Toronto", "America/Winnipeg", "America/Regina",
        "America/Edmonton", "America/Vancouver", "America/Whitehorse",
        "America/Iqaluit",
    ]),
    ("Cayman Islands", ["America/Cayman"]),
    ("Chile", ["America/Santiago", "America/Punta_Arenas", "Pacific/Easter"]),
    ("Colombia", ["America/Bogota"]),
    ("Costa Rica", ["America/Costa_Rica"]),
    ("Cuba", ["America/Havana"]),
    ("Curaçao", ["America/Curacao"]),
    ("Dominica", ["America/Dominica"]),
    ("Dominican Republic", ["America/Santo_Domingo"]),
    ("Ecuador", ["America/Guayaquil", "Pacific/Galapagos"]),
    ("El Salvador", ["America/El_Salvador"]),
    ("Falkland Islands", ["Atlantic/Stanley"]),
    ("French Guiana", ["America/Cayenne"]),
    ("Greenland", [
        "America/Nuuk", "America/Danmarkshavn", "America/Scoresbysund",
        "America/Thule",
    ]),
    ("Grenada", ["America/Grenada"]),
    ("Guadeloupe", ["America/Guadeloupe"]),
    ("Guatemala", ["America/Guatemala"]),
    ("Guyana", ["America/Guyana"]),
    ("Haiti", ["America/Port-au-Prince"]),
    ("Honduras", ["America/Tegucigalpa"]),
    ("Jamaica", ["America/Jamaica"]),
    ("Martinique", ["America/Martinique"]),
    ("Mexico", [
        "America/Mexico_City", "America/Cancun", "America/Merida",
        "America/Monterrey", "America/Chihuahua", "America/Mazatlan",
        "America/Hermosillo", "America/Tijuana",
    ]),
    ("Montserrat", ["America/Montserrat"]),
    ("Nicaragua", ["America/Managua"]),
    ("Panama", ["America/Panama"]),
    ("Paraguay", ["America/Asuncion"]),
    ("Peru", ["America/Lima"]),
    ("Puerto Rico", ["America/Puerto_Rico"]),
    ("Saint Barthélemy", ["America/St_Barthelemy"]),
    ("Saint Kitts and Nevis", ["America/St_Kitts"]),
    ("Saint Lucia", ["America/St_Lucia"]),
    ("Saint Martin", ["America/Marigot"]),
    ("Saint Pierre and Miquelon", ["America/Miquelon"]),
    ("Saint Vincent and the Grenadines", ["America/St_Vincent"]),
    ("Sint Maarten", ["America/Lower_Princes"]),
    ("Suriname", ["America/Paramaribo"]),
    ("Trinidad and Tobago", ["America/Port_of_Spain"]),
    ("Turks and Caicos Islands", ["America/Grand_Turk"]),
    ("United States", [
        "America/New_York", "America/Detroit",
        "America/Indiana/Indianapolis", "America/Chicago",
        "America/Denver", "America/Phoenix", "America/Los_Angeles",
        "America/Anchorage", "America/Juneau", "America/Adak",
        "Pacific/Honolulu",
    ]),
    ("Uruguay", ["America/Montevideo"]),
    ("U.S. Virgin Islands", ["America/St_Thomas"]),
    ("Venezuela", ["America/Caracas"]),

    # ---- Asia ----
    ("Afghanistan", ["Asia/Kabul"]),
    ("Armenia", ["Asia/Yerevan"]),
    ("Azerbaijan", ["Asia/Baku"]),
    ("Bahrain", ["Asia/Bahrain"]),
    ("Bangladesh", ["Asia/Dhaka"]),
    ("Bhutan", ["Asia/Thimphu"]),
    ("British Indian Ocean Territory", ["Indian/Chagos"]),
    ("Brunei", ["Asia/Brunei"]),
    ("Cambodia", ["Asia/Phnom_Penh"]),
    ("China", ["Asia/Shanghai", "Asia/Urumqi"]),
    ("Cyprus", ["Asia/Nicosia", "Asia/Famagusta"]),
    ("Georgia", ["Asia/Tbilisi"]),
    ("Hong Kong", ["Asia/Hong_Kong"]),
    ("India", ["Asia/Kolkata"]),
    ("Indonesia", [
        "Asia/Jakarta", "Asia/Pontianak", "Asia/Makassar", "Asia/Jayapura",
    ]),
    ("Iran", ["Asia/Tehran"]),
    ("Iraq", ["Asia/Baghdad"]),
    ("Israel", ["Asia/Jerusalem"]),
    ("Japan", ["Asia/Tokyo"]),
    ("Jordan", ["Asia/Amman"]),
    ("Kazakhstan", [
        "Asia/Almaty", "Asia/Qostanay", "Asia/Qyzylorda", "Asia/Aqtobe",
        "Asia/Aqtau", "Asia/Atyrau", "Asia/Oral",
    ]),
    ("Kuwait", ["Asia/Kuwait"]),
    ("Kyrgyzstan", ["Asia/Bishkek"]),
    ("Laos", ["Asia/Vientiane"]),
    ("Lebanon", ["Asia/Beirut"]),
    ("Macao", ["Asia/Macau"]),
    ("Malaysia", ["Asia/Kuala_Lumpur", "Asia/Kuching"]),
    ("Maldives", ["Indian/Maldives"]),
    ("Mongolia", ["Asia/Ulaanbaatar", "Asia/Hovd", "Asia/Choibalsan"]),
    ("Myanmar", ["Asia/Yangon"]),
    ("Nepal", ["Asia/Kathmandu"]),
    ("North Korea", ["Asia/Pyongyang"]),
    ("Oman", ["Asia/Muscat"]),
    ("Pakistan", ["Asia/Karachi"]),
    ("Palestine", ["Asia/Gaza", "Asia/Hebron"]),
    ("Philippines", ["Asia/Manila"]),
    ("Qatar", ["Asia/Qatar"]),
    ("Russia", [
        "Europe/Kaliningrad", "Europe/Moscow", "Europe/Volgograd",
        "Europe/Samara", "Asia/Yekaterinburg", "Asia/Omsk",
        "Asia/Novosibirsk", "Asia/Krasnoyarsk", "Asia/Irkutsk",
        "Asia/Yakutsk", "Asia/Vladivostok", "Asia/Magadan",
        "Asia/Sakhalin", "Asia/Kamchatka",
    ]),
    ("Saudi Arabia", ["Asia/Riyadh"]),
    ("Singapore", ["Asia/Singapore"]),
    ("South Korea", ["Asia/Seoul"]),
    ("Sri Lanka", ["Asia/Colombo"]),
    ("Syria", ["Asia/Damascus"]),
    ("Taiwan", ["Asia/Taipei"]),
    ("Tajikistan", ["Asia/Dushanbe"]),
    ("Thailand", ["Asia/Bangkok"]),
    ("Timor-Leste", ["Asia/Dili"]),
    ("Turkey", ["Europe/Istanbul"]),
    ("Turkmenistan", ["Asia/Ashgabat"]),
    ("United Arab Emirates", ["Asia/Dubai"]),
    ("Uzbekistan", ["Asia/Tashkent", "Asia/Samarkand"]),
    ("Vietnam", ["Asia/Ho_Chi_Minh"]),
    ("Yemen", ["Asia/Aden"]),

    # ---- Europe ----
    ("Åland Islands", ["Europe/Mariehamn"]),
    ("Albania", ["Europe/Tirane"]),
    ("Andorra", ["Europe/Andorra"]),
    ("Austria", ["Europe/Vienna"]),
    ("Belarus", ["Europe/Minsk"]),
    ("Belgium", ["Europe/Brussels"]),
    ("Bosnia and Herzegovina", ["Europe/Sarajevo"]),
    ("Bulgaria", ["Europe/Sofia"]),
    ("Croatia", ["Europe/Zagreb"]),
    ("Czechia", ["Europe/Prague"]),
    ("Denmark", ["Europe/Copenhagen"]),
    ("Estonia", ["Europe/Tallinn"]),
    ("Faroe Islands", ["Atlantic/Faroe"]),
    ("Finland", ["Europe/Helsinki"]),
    ("France", ["Europe/Paris"]),
    ("Germany", ["Europe/Berlin"]),
    ("Gibraltar", ["Europe/Gibraltar"]),
    ("Greece", ["Europe/Athens"]),
    ("Guernsey", ["Europe/Guernsey"]),
    ("Hungary", ["Europe/Budapest"]),
    ("Iceland", ["Atlantic/Reykjavik"]),
    ("Ireland", ["Europe/Dublin"]),
    ("Isle of Man", ["Europe/Isle_of_Man"]),
    ("Italy", ["Europe/Rome"]),
    ("Jersey", ["Europe/Jersey"]),
    ("Latvia", ["Europe/Riga"]),
    ("Liechtenstein", ["Europe/Vaduz"]),
    ("Lithuania", ["Europe/Vilnius"]),
    ("Luxembourg", ["Europe/Luxembourg"]),
    ("Malta", ["Europe/Malta"]),
    ("Moldova", ["Europe/Chisinau"]),
    ("Monaco", ["Europe/Monaco"]),
    ("Montenegro", ["Europe/Podgorica"]),
    ("Netherlands", ["Europe/Amsterdam"]),
    ("North Macedonia", ["Europe/Skopje"]),
    ("Norway", ["Europe/Oslo"]),
    ("Poland", ["Europe/Warsaw"]),
    ("Portugal", ["Europe/Lisbon", "Atlantic/Madeira", "Atlantic/Azores"]),
    ("Romania", ["Europe/Bucharest"]),
    ("San Marino", ["Europe/San_Marino"]),
    ("Serbia", ["Europe/Belgrade"]),
    ("Slovakia", ["Europe/Bratislava"]),
    ("Slovenia", ["Europe/Ljubljana"]),
    ("Spain", ["Europe/Madrid", "Africa/Ceuta", "Atlantic/Canary"]),
    ("Svalbard and Jan Mayen", ["Arctic/Longyearbyen"]),
    ("Sweden", ["Europe/Stockholm"]),
    ("Switzerland", ["Europe/Zurich"]),
    ("Ukraine", ["Europe/Kyiv"]),
    ("United Kingdom", ["Europe/London"]),
    ("Vatican City", ["Europe/Vatican"]),

    # ---- Oceania ----
    ("American Samoa", ["Pacific/Pago_Pago"]),
    ("Australia", [
        "Australia/Sydney", "Australia/Melbourne", "Australia/Brisbane",
        "Australia/Adelaide", "Australia/Perth", "Australia/Hobart",
        "Australia/Darwin", "Australia/Broken_Hill", "Australia/Lord_Howe",
        "Australia/Eucla",
    ]),
    ("Christmas Island", ["Indian/Christmas"]),
    ("Cocos (Keeling) Islands", ["Indian/Cocos"]),
    ("Cook Islands", ["Pacific/Rarotonga"]),
    ("Fiji", ["Pacific/Fiji"]),
    ("French Polynesia", [
        "Pacific/Tahiti", "Pacific/Marquesas", "Pacific/Gambier",
    ]),
    ("Guam", ["Pacific/Guam"]),
    ("Kiribati", ["Pacific/Tarawa", "Pacific/Kanton", "Pacific/Kiritimati"]),
    ("Marshall Islands", ["Pacific/Majuro", "Pacific/Kwajalein"]),
    ("Micronesia", ["Pacific/Chuuk", "Pacific/Pohnpei", "Pacific/Kosrae"]),
    ("Nauru", ["Pacific/Nauru"]),
    ("New Caledonia", ["Pacific/Noumea"]),
    ("New Zealand", ["Pacific/Auckland", "Pacific/Chatham"]),
    ("Niue", ["Pacific/Niue"]),
    ("Norfolk Island", ["Pacific/Norfolk"]),
    ("Northern Mariana Islands", ["Pacific/Saipan"]),
    ("Palau", ["Pacific/Palau"]),
    ("Papua New Guinea", [
        "Pacific/Port_Moresby", "Pacific/Bougainville",
    ]),
    ("Pitcairn Islands", ["Pacific/Pitcairn"]),
    ("Samoa", ["Pacific/Apia"]),
    ("Solomon Islands", ["Pacific/Guadalcanal"]),
    ("Tokelau", ["Pacific/Fakaofo"]),
    ("Tonga", ["Pacific/Tongatapu"]),
    ("Tuvalu", ["Pacific/Funafuti"]),
    ("Vanuatu", ["Pacific/Efate"]),
    ("Wallis and Futuna", ["Pacific/Wallis"]),
]


# Names a browser may report that the list above files under something
# else. A browser in Delhi says "Asia/Calcutta"; the list, and IANA
# itself these days, says "Asia/Kolkata". Both are real and both give the
# same time, but only one of them is in the picker - and a cafe whose
# stored zone is not in the picker opens the page to find nothing chosen.
#
# Only aliases that point somewhere the list actually offers. Anything
# else is left exactly as it is: an unrecognised name that the machine
# still resolves keeps working, and the picker carries it as an extra
# entry rather than dropping it.
ZONE_ALIASES = {
    "Asia/Calcutta": "Asia/Kolkata",
    "Asia/Katmandu": "Asia/Kathmandu",
    "Asia/Rangoon": "Asia/Yangon",
    "Asia/Saigon": "Asia/Ho_Chi_Minh",
    "Asia/Dacca": "Asia/Dhaka",
    "Asia/Thimbu": "Asia/Thimphu",
    "Asia/Ashkhabad": "Asia/Ashgabat",
    "Asia/Ulan_Bator": "Asia/Ulaanbaatar",
    "Asia/Chongqing": "Asia/Shanghai",
    "Asia/Chungking": "Asia/Shanghai",
    "Asia/Harbin": "Asia/Shanghai",
    "Asia/Kashgar": "Asia/Urumqi",
    "Asia/Macao": "Asia/Macau",
    "Asia/Tel_Aviv": "Asia/Jerusalem",
    "Asia/Istanbul": "Europe/Istanbul",
    "Europe/Nicosia": "Asia/Nicosia",
    "Europe/Kiev": "Europe/Kyiv",
    "Europe/Uzhgorod": "Europe/Kyiv",
    "Europe/Zaporozhye": "Europe/Kyiv",
    "Europe/Belfast": "Europe/London",
    "Europe/Tiraspol": "Europe/Chisinau",
    "America/Buenos_Aires": "America/Argentina/Buenos_Aires",
    "America/Cordoba": "America/Argentina/Cordoba",
    "America/Rosario": "America/Argentina/Cordoba",
    "America/Mendoza": "America/Argentina/Mendoza",
    "America/Jujuy": "America/Argentina/Salta",
    "America/Catamarca": "America/Argentina/Salta",
    "America/Indianapolis": "America/Indiana/Indianapolis",
    "America/Fort_Wayne": "America/Indiana/Indianapolis",
    "America/Louisville": "America/New_York",
    "America/Montreal": "America/Toronto",
    "America/Nipigon": "America/Toronto",
    "America/Thunder_Bay": "America/Toronto",
    "America/Rainy_River": "America/Winnipeg",
    "America/Yellowknife": "America/Edmonton",
    "America/Atikokan": "America/Panama",
    "America/Coral_Harbour": "America/Panama",
    "America/Santa_Isabel": "America/Tijuana",
    "America/Ensenada": "America/Tijuana",
    "America/Godthab": "America/Nuuk",
    "America/Virgin": "America/St_Thomas",
    "America/Shiprock": "America/Denver",
    "America/Knox_IN": "America/Chicago",
    "Africa/Timbuktu": "Africa/Bamako",
    "Africa/Asmera": "Africa/Asmara",
    "Atlantic/Jan_Mayen": "Arctic/Longyearbyen",
    "Atlantic/Faeroe": "Atlantic/Faroe",
    "Pacific/Ponape": "Pacific/Pohnpei",
    "Pacific/Truk": "Pacific/Chuuk",
    "Pacific/Yap": "Pacific/Chuuk",
    "Pacific/Samoa": "Pacific/Pago_Pago",
    "Pacific/Johnston": "Pacific/Honolulu",
    "Pacific/Enderbury": "Pacific/Kanton",
    "Australia/ACT": "Australia/Sydney",
    "Australia/NSW": "Australia/Sydney",
    "Australia/Canberra": "Australia/Sydney",
    "Australia/Victoria": "Australia/Melbourne",
    "Australia/Queensland": "Australia/Brisbane",
    "Australia/South": "Australia/Adelaide",
    "Australia/West": "Australia/Perth",
    "Australia/Tasmania": "Australia/Hobart",
    "Australia/North": "Australia/Darwin",
    "Australia/LHI": "Australia/Lord_Howe",
    "Australia/Yancowinna": "Australia/Broken_Hill",
    # The short country-code spellings, which some browsers still use.
    "Hongkong": "Asia/Hong_Kong",
    "Iceland": "Atlantic/Reykjavik",
    "Israel": "Asia/Jerusalem",
    "Jamaica": "America/Jamaica",
    "Japan": "Asia/Tokyo",
    "Kwajalein": "Pacific/Kwajalein",
    "Libya": "Africa/Tripoli",
    "Navajo": "America/Denver",
    "Poland": "Europe/Warsaw",
    "Portugal": "Europe/Lisbon",
    "Singapore": "Asia/Singapore",
    "Turkey": "Europe/Istanbul",
    "Egypt": "Africa/Cairo",
    "Eire": "Europe/Dublin",
    "Cuba": "America/Havana",
    "GB": "Europe/London",
    "GB-Eire": "Europe/London",
    "PRC": "Asia/Shanghai",
    "ROC": "Asia/Taipei",
    "ROK": "Asia/Seoul",
    "NZ": "Pacific/Auckland",
    "NZ-CHAT": "Pacific/Chatham",
    "W-SU": "Europe/Moscow",
    "Zulu": "UTC",
    "Universal": "UTC",
    "Greenwich": "UTC",
    "GMT": "UTC",
    "GMT0": "UTC",
    "GMT+0": "UTC",
    "GMT-0": "UTC",
    "Etc/UTC": "UTC",
    "Etc/GMT": "UTC",
    "Etc/Greenwich": "UTC",
    "Etc/Universal": "UTC",
    "Etc/Zulu": "UTC",
}


def city_of(zone):
    """
    The part of a zone name people would recognise.

    "America/Argentina/Buenos_Aires" -> "Buenos Aires". Only ever shown
    beside a country that keeps more than one clock, where the country's
    name alone would not say which.
    """
    return zone.rsplit("/", 1)[-1].replace("_", " ")
